# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

## Author
Joseph Frenette

**Objectives:**


*   List popular languages for Data Science
*   List popular open-source libraries for Data Science
*   List popular development environments

Some of the popular languages that Data Scientists use are:




1.   SQL
2.   Python
3.   R

Some of the commonly used libraries used by Data Scientists include:



1.   Pandas
2.   Numpy
3.   Seaborn

| Data Science Tools |
| -------- |
| TensorFlow |
| Matplotlib |
| Scikitlearn|

### Below are a few examples of evaluating arithmetic expressions in Python

In [3]:
#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

17

In [4]:
# This will convert 200 minutes to hours by diving by 60
200/60

3.3333333333333335